# BSE Configuration File - Generated by BSE Settings GUI

n_days = 0.01
hours_in_a_day = 24.0

# Trader specifications
buyers_spec = [('SHVR', 5), ('GVWY', 5), ('ZIC', 2), ('ZIP', 13)]
sellers_spec = buyers_spec

# Output settings
n_trials = 10
n_trials_recorded = 1
dump_flags = {'dump_blotters': False, 'dump_lobs': False, 'dump_strats': False, 'dump_avgbals': True, 'dump_tape': False}
