# BSE Configuration File - Generated by BSE Settings GUI

n_days = 0.01
hours_in_a_day = 24.0

# Trader specifications
buyers_spec = [('SHVR', 4), ('GVWY', 80), ('SNPR', 40), ('ZIC', 4), ('ZIP', 40)]
sellers_spec = [('SHVR', 1), ('GVWY', 20), ('SNPR', 10), ('ZIC', 1), ('ZIP', 10)]

# Output settings
n_trials = 1
n_trials_recorded = 1
dump_flags = {'dump_blotters': False, 'dump_lobs': False, 'dump_strats': False, 'dump_avgbals': True, 'dump_tape': False}
